<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <AssemblyName>Mc.Rules</AssemblyName>
    <RootNamespace>Mc.Rules</RootNamespace>
    <Version>0.1.0-alpha</Version>
    <Authors>Cpmf</Authors>
    <PackageLicenseExpression>CC-BY-4.0</PackageLicenseExpression>
    <PackageDescription>Mc workflow analyzer rule library.</PackageDescription>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WatchfulAnvil.Sdk\WatchfulAnvil.Sdk.csproj">
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="UiPath.Activities.Api" Version="23.10.3">
      <ExcludeAssets>runtime</ExcludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="UiPath.Activities.Api" Version="24.10.1">
      <ExcludeAssets>runtime</ExcludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
