//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPRIMA.WorkflowAnalyzerRules.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPRIMA.WorkflowAnalyzerRules.LocalizationResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Operation Rule.
        /// </summary>
        public static string CPM_NOOP_000_Name {
            get {
                return ResourceManager.GetString("CPM_NOOP_000_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule does nothing and always passes..
        /// </summary>
        public static string CPM_NOOP_000_Recommendation {
            get {
                return ResourceManager.GetString("CPM_NOOP_000_Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Project Rule.
        /// </summary>
        public static string CPM_NOOP_001_Name {
            get {
                return ResourceManager.GetString("CPM_NOOP_001_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule does nothing and always passes..
        /// </summary>
        public static string CPM_NOOP_001_Recommendation {
            get {
                return ResourceManager.GetString("CPM_NOOP_001_Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Workflow Rule.
        /// </summary>
        public static string CPM_NOOP_002_Name {
            get {
                return ResourceManager.GetString("CPM_NOOP_002_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule does nothing and always passes..
        /// </summary>
        public static string CPM_NOOP_002_Recommendation {
            get {
                return ResourceManager.GetString("CPM_NOOP_002_Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Activity Rule.
        /// </summary>
        public static string CPM_NOOP_003_Name {
            get {
                return ResourceManager.GetString("CPM_NOOP_003_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule does nothing and always passes..
        /// </summary>
        public static string CPM_NOOP_003_Recommendation {
            get {
                return ResourceManager.GetString("CPM_NOOP_003_Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure ShouldStop Activity Usage.
        /// </summary>
        public static string CPM_USG_000_Name {
            get {
                return ResourceManager.GetString("CPM_USG_000_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project must include at least one &apos;ShouldStop&apos; activity..
        /// </summary>
        public static string CPM_USG_000_Recommendation {
            get {
                return ResourceManager.GetString("CPM_USG_000_Recommendation", resourceCulture);
            }
        }
    }
}
