// Shared_Defines.iss
// This file defines shared constants for Inno Setup scripts.
// Most version-related values are sourced from version.generated.iss,
// which is auto-generated by WatchfulAnvilInstaller_GenerateVersion.ps1.

#include "version.generated.iss"

// Constants NOT auto-generated (safe to edit here)

// OutputDir is relative to /installer/
#define OutputDir "output"
